version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgis:
    image: mdillon/postgis
    ports:
      - '5432:5432'
    # volumes:
      # - $HOME/postgres_data:/var/lib/postgresql/data
  geoserver:
    build:
      context: .
      args:
        ORACLE_JDK: "true"
        GS_VERSION: "2.10.1"
    depends_on:
      - postgis
      - kafka
    environment:
      - VIRTUAL_HOST=geoserver
      - JAVA_OPTS=-Xmx1536M -XX:MaxPermSize=756M -Dbootstrap.servers=kafka:9092 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000
    ports:
      - '8080:8080'
      - '8000:8000'
    # volumes:
      # - $HOME/geoserver_data:/opt/geoserver/data_dir
